-- 0051_fact_display_gloss.sql — an English display string for a source-language fact.
--
-- fact.value is stored in the SOURCE language on purpose: extraction runs on the raw
-- chapter, evidence anchors into that immutable content-hashed text, and facts are
-- append-only (§0.1). A translation is none of those things -- it is regenerated by a
-- retry, a model swap, or a forward-only glossary correction -- so extracting facts FROM
-- the English would bind append-only rows to a string that can stop existing.
--
-- The consequence was that a reader saw Chinese in the entity card. This closes that
-- without moving extraction: value_en is a DISPLAY gloss produced by the same extraction
-- call that produced value, and it is never evidence. Semantic verification continues to
-- check support for `value` against the source alone; value_en gates nothing, so a bad
-- gloss is a cosmetic bug you overwrite, not graph corruption that needs the repair path.
--
-- Nullable with a read-path COALESCE fallback, so every fact already in the table keeps
-- rendering exactly as it does today rather than blanking out.
BEGIN;

ALTER TABLE fact ADD COLUMN value_en TEXT;

COMMENT ON COLUMN fact.value_en IS
  'Display-only English gloss of value. Never evidence, never gated on, may be NULL.';

-- The live proposal panel reads the raw model response, so it gets the gloss for free;
-- it just has to prefer it. Same COALESCE discipline as the served read paths.
CREATE OR REPLACE FUNCTION repair_proposed_claims(novel UUID)
RETURNS TABLE(kind TEXT, attribute TEXT, value TEXT, quote TEXT, mentions INT)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT c->>'type', c->>'attribute', coalesce(c->>'value_en', c->>'value'), c->>'quote',
         coalesce(jsonb_array_length(c->'mention_ids'), 0)
    FROM graph_completion g,
         LATERAL jsonb_array_elements(g.response->'claims') c
   WHERE g.revision_id = repair_subject_revision(novel, 'graph')
     AND jsonb_typeof(g.response->'claims') = 'array'
   LIMIT 40
$$;

-- CREATE OR REPLACE preserves owner and grants; re-asserted so this file stands alone.
ALTER FUNCTION repair_proposed_claims(UUID) OWNER TO repair_reporter;
REVOKE EXECUTE ON FUNCTION repair_proposed_claims(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION repair_proposed_claims(UUID) TO repair_operator;

COMMIT;
