"""Occurrence identities and literal evidence validation. No database/model side effects.

Offsets count Unicode code points, like textproc and the reader. A source name is
never a binding key: two occurrences with identical spelling may name different people.
"""
from __future__ import annotations

import hashlib
import json
import re
from typing import Literal
from uuid import NAMESPACE_URL, uuid5

from pydantic import BaseModel, ConfigDict, Field

PROMPT_VERSION = 'evidence-v13-display-gloss'

MAX_EXPLANATION_CHARS = 200
MAX_FACT_VALUE_CHARS = 400
# The display gloss is deliberately shorter than the value it renders: it exists to be
# readable in a hover card, and every extra output token it costs is a token closer to
# the response cap that would truncate the whole claims batch into a contract rejection.
MAX_FACT_GLOSS_CHARS = 200


def digest(value) -> str:
    text = value if isinstance(value, str) else json.dumps(value, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(text.encode()).hexdigest()


def stable_id(*parts) -> str:
    return str(uuid5(NAMESPACE_URL, json.dumps(parts, ensure_ascii=False)))


class Strict(BaseModel):
    model_config = ConfigDict(extra='forbid')


class Supported(Strict):
    quote: str
    # Set by the application from an offered passage, never generated by the model.
    evidence_start: int | None = Field(default=None, ge=0)


class Name(Supported):
    surface: str = Field(max_length=80)
    kind: str
    quote: str = Field(max_length=400)
    named: bool


class Names(Strict):
    # Each model request is capped at 12 names by its wire schema. Application-owned
    # aggregation spans as many bounded passage batches as a long chapter needs.
    names: list[Name]
    reviewed_kinds: list[str] = Field(default_factory=list)
    rejected: list[dict] = Field(default_factory=list)


class Decision(Supported):
    mention_id: str
    outcome: Literal['existing', 'new', 'unresolved']
    # Existing: offered entity ID. New: offered representative mention ID.
    target_id: str | None
    quote: str
    reason: str = Field(max_length=MAX_EXPLANATION_CHARS)


class Claim(Supported):
    type: Literal['fact', 'relationship', 'event']
    mention_ids: list[str] = Field(min_length=1)
    attribute: str
    value: str = Field(max_length=MAX_FACT_VALUE_CHARS)
    # Display only. `value` stays source-language and is the only thing verification
    # checks against the evidence; an absent or wrong gloss never blocks publication.
    value_en: str = Field(default='', max_length=MAX_FACT_GLOSS_CHARS)
    quote: str


class Proposals(Strict):
    decisions: list[Decision]
    claims: list[Claim]


class IdentityDecision(Strict):
    """Bounded model wire decision; refs exist only for one request."""

    occurrence_ref: str
    outcome: Literal['existing', 'new', 'unresolved']
    target_ref: str | None
    reason_code: Literal[
        'existing_evidence', 'new_first_appearance', 'new_coreference',
        'ambiguous', 'insufficient_evidence',
    ]
    explanation: str = Field(max_length=MAX_EXPLANATION_CHARS)
    # Materialized from an application-offered passage reference.
    quote: str
    evidence_start: int | None = Field(default=None, ge=0)


class IdentityDecisions(Strict):
    decisions: list[IdentityDecision]


class ClaimProposal(Strict):
    """Bounded model wire claim; occurrence refs exist only for one request."""

    type: Literal['fact', 'relationship', 'event']
    occurrence_refs: list[str] = Field(min_length=1)
    attribute: str
    value: str = Field(max_length=MAX_FACT_VALUE_CHARS)
    # Required on the wire, unlike on Claim: an optional property is one the model can
    # quietly stop emitting, and a grammar slot it must fill is the cheapest guarantee
    # that a gloss actually arrives. Empty string is the honest "cannot render this".
    value_en: str = Field(max_length=MAX_FACT_GLOSS_CHARS)
    quote: str
    evidence_start: int | None = Field(default=None, ge=0)


class ClaimProposals(Strict):
    claims: list[ClaimProposal] = Field(max_length=12)


class Alignment(Supported):
    phrase: str
    occurrence: int = Field(ge=0)
    mention_id: str | None
    quote: str


class Alignments(Strict):
    alignments: list[Alignment]


class Verdict(Strict):
    id: str
    supported: bool
    reason: str = Field(max_length=MAX_EXPLANATION_CHARS)


class Verification(Strict):
    verdicts: list[Verdict]


def passage(text: str, quote: str, *, anchor: int | None = None, start: int | None = None) -> dict | None:
    """Return only exact evidence; ambiguous repeated quotations need an anchor."""
    if not quote or not quote.strip():
        return None
    if start is not None:
        # Exact offsets resolve repeated passages without fuzzy matching or quote repair.
        starts = [start] if 0 <= start and text[start:start+len(quote)] == quote else []
    else:
        starts = [m.start() for m in re.finditer(re.escape(quote), text)]
    if anchor is not None:
        starts = [start for start in starts if start <= anchor < start + len(quote)]
    if len(starts) != 1:
        return None
    return dict(char_start=starts[0], char_end=starts[0]+len(quote), quote=quote)


def source_mentions(novel: str, chapter: int, source: str, names: Names, ontology: dict) -> list[dict]:
    found = {}
    conflicting = set()
    for name in names.names:
        if not name.named or name.kind not in ontology['kinds'] or not name.surface.strip():
            continue
        # Generic titles/pronouns can be contextual mentions, never reusable identities.
        if name.surface.casefold() in {'he','she','they','master','elder','father','mother','他','她','长老','师父','父亲','母亲'}:
            continue
        if name.surface not in name.quote or not passage(source, name.quote, start=name.evidence_start):
            continue
        for match in re.finditer(re.escape(name.surface), source):
            start, end = match.span()
            if not re.search(r'[㐀-䶿一-鿿豈-﫿]',name.surface):
                word=lambda ch: ch.isalnum() or ch=='_'
                if ((word(name.surface[0]) and start>0 and word(source[start-1]))
                    or (word(name.surface[-1]) and end<len(source) and word(source[end]))):
                    continue
            # Supply local context for EACH occurrence; don't bind all homonyms together.
            left = max(source.rfind('。', 0, start), source.rfind('\n', 0, start)) + 1
            right = source.find('。', end)
            right = min(len(source), right+1 if right >= 0 else end+180)
            quote = source[left:right]
            mid = stable_id(novel, chapter, digest(source), start, end)
            if mid in conflicting:
                continue
            if mid in found and found[mid]['kind']!=name.kind:
                # Conflicting proposed kinds cannot be resolved by list order.
                del found[mid]
                conflicting.add(mid)
                continue
            found[mid] = dict(id=mid, surface=name.surface, kind=name.kind,
                              char_start=start, char_end=end, quote=quote,
                              context_start=left, context_end=right)
    return sorted(found.values(), key=lambda m: m['char_start'])


def validate_proposals(source: str, mentions: list[dict], candidates: list[dict] | dict[str, list[dict]],
                       proposals: Proposals, ontology: dict) -> tuple[list[dict], list[dict]]:
    offered = {m['id']: m for m in mentions}
    if isinstance(candidates, dict):
        per_mention = {
            mention_id: {candidate['id']: candidate for candidate in rows}
            for mention_id, rows in candidates.items()
        }
        entities = {candidate_id: candidate for rows in per_mention.values()
                    for candidate_id, candidate in rows.items()}
    else:
        entities = {c['id']: c for c in candidates}
        per_mention = {mention_id: entities for mention_id in offered}
    accepted, rejected = [], []
    seen = set()
    for i, d in enumerate(proposals.decisions):
        m = offered.get(d.mention_id)
        why = None
        if not m or d.mention_id in seen:
            why = 'unknown or duplicate mention ID'
        elif d.outcome == 'unresolved':
            seen.add(d.mention_id)
            continue
        elif not passage(source, d.quote, anchor=m['char_start'], start=d.evidence_start):
            why = 'identity evidence does not include this occurrence'
        elif d.outcome == 'existing':
            c = per_mention.get(d.mention_id, {}).get(d.target_id)
            if not c or c['kind'] != m['kind']:
                why = 'invented candidate ID or incompatible kind'
        elif d.outcome == 'new':
            root = offered.get(d.target_id)
            if not root or root['kind'] != m['kind']:
                why = 'new identity must reference an offered mention of the same kind'
        seen.add(d.mention_id)
        item = dict(id=f'identity:{i}', **d.model_dump())
        (rejected if why else accepted).append(dict(item, rejection=why) if why else item)
    for i, c in enumerate(proposals.claims):
        why = None
        if any(mid not in offered for mid in c.mention_ids):
            why = 'claim references an unoffered mention ID'
        elif not passage(source, c.quote, start=c.evidence_start):
            why = 'claim evidence is absent or ambiguous'
        elif c.type == 'fact':
            if len(c.mention_ids) != 1 or not any(
                a['name'] == c.attribute and offered[c.mention_ids[0]]['kind'] in a['kinds']
                for a in ontology['attributes']):
                why = 'invalid attribute or entity kind'
        elif c.type == 'relationship' and (len(c.mention_ids) != 2 or c.attribute not in ontology['relations']):
            why = 'invalid relationship'
        item = dict(id=f'claim:{i}', **c.model_dump())
        (rejected if why else accepted).append(dict(item, rejection=why) if why else item)
    return accepted, rejected


def approved(items: list[dict], verification: Verification) -> tuple[list[dict], list[dict]]:
    """Missing, repeated, or negative verdicts fail closed."""
    verdicts: dict[str, list[Verdict]] = {}
    for v in verification.verdicts:
        verdicts.setdefault(v.id, []).append(v)
    yes, no = [], []
    for item in items:
        vs = verdicts.get(item['id'], [])
        if len(vs) == 1 and vs[0].supported:
            yes.append(item)
        else:
            no.append(dict(item, rejection=vs[0].reason if len(vs)==1 else 'missing or duplicate verification'))
    return yes, no


def aligned_mentions(novel: str, chapter: int, source: str, display: str,
                     mentions: list[dict], alignment: Alignments, *,
                     display_offset: int = 0, display_identity: str | None = None) -> list[dict]:
    offered = {m['id']: m for m in mentions}
    spans = {}
    for a in alignment.alignments:
        if not a.phrase.strip():
            continue
        matches = list(re.finditer(re.escape(a.phrase), display))
        if a.occurrence >= len(matches):
            continue
        start, end = matches[a.occurrence].span()
        start, end = start+display_offset, end+display_offset
        mid = a.mention_id
        m = offered.get(mid)
        ev = passage(source, a.quote, anchor=m['char_start'], start=a.evidence_start) if m else None
        # Invalid alignment still yields an empty clickable card, never a guessed link.
        item = dict(id=stable_id(novel,chapter,display_identity or digest(display),start,end),
                    char_start=start,char_end=end,phrase=a.phrase,
                    mention_id=mid if ev else None,quote=a.quote if ev else None,
                    evidence_start=a.evidence_start if ev else None)
        key = (start,end)
        if key in spans and spans[key]['mention_id'] != item['mention_id']:
            item['mention_id'] = item['quote'] = None
        spans[key] = item
    result = []
    for item in sorted(spans.values(), key=lambda s: (s['char_start'], -s['char_end'])):
        if result and item['char_start'] < result[-1]['char_end']:
            continue
        result.append(item)
    return result
