"""Occurrence identities and literal evidence validation. No database/model side effects.

Offsets count Unicode code points, like textproc and the reader. A source name is
never a binding key: two occurrences with identical spelling may name different people.
"""
from __future__ import annotations

import hashlib
import json
import re
from typing import Literal
from uuid import NAMESPACE_URL, uuid5

from pydantic import BaseModel, ConfigDict, Field

# Word-boundary checks must not apply Latin isalnum() adjacency rules to CJK
# surfaces: Python's str.isalnum() is True for Han characters, so an unguarded
# check would reject nearly every occurrence in zh source text (no spaces mean
# every name is "surrounded" by alnum characters). Shared by source_mentions()
# below and passages.py's extract materializer -- both must agree, or an
# attribute/relation/occurrence's anchored reference silently fails to match any
# mention_id source_mentions() produced.
CJK_RE = re.compile(r'[㐀-䶿一-鿿豈-﫿]')

MAX_EXPLANATION_CHARS = 200
MAX_FACT_VALUE_CHARS = 400
# The display gloss is deliberately shorter than the value it renders: it exists to be
# readable in a hover card, and every extra output token it costs is a token closer to
# the response cap that would truncate the whole claims batch into a contract rejection.
MAX_FACT_GLOSS_CHARS = 200


def digest(value) -> str:
    text = value if isinstance(value, str) else json.dumps(value, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(text.encode()).hexdigest()


# Each stage keeps its own compatibility marker.  The prompt text and wire schema are
# also part of the request digest, so these values are only needed when a materializer
# changes while its visible prompt text does not.  Keeping that distinction explicit
# prevents a future maintainer from deleting this map as redundant.
# B.6 collapses the pipeline to four surviving stages for an unsplit chapter: the
# merged 'extract' pass, 'identity_slots' (bounded identity proposals), 'verify'
# (semantic identity verification -- the one verifier B.6 keeps), and 'align'.
# 'names', 'name_slots', 'claims', 'evidence', 'fact_verify', 'fact_review',
# 'render', 'render_verify', 'propose' and 'name_verify' are dropped; 'verify' no
# longer serves claims or alignment, only identity.
STAGE_PROMPT_VERSIONS = {
    stage: 'evidence-v21-merged-extract'
    for stage in ('extract', 'identity_slots', 'verify', 'align')
}

# graph_revision.prompt_version is a digest of the stage map.  The old single marker is
# retained as a compatible drift source for revisions created before the map existed.
LEGACY_PROMPT_VERSION = 'evidence-v20-compact-identity-wire'
PROMPT_VERSION = digest(STAGE_PROMPT_VERSIONS)


def stable_id(*parts) -> str:
    return str(uuid5(NAMESPACE_URL, json.dumps(parts, ensure_ascii=False)))


class Strict(BaseModel):
    model_config = ConfigDict(extra='forbid')


class Supported(Strict):
    quote: str
    # Set by the application from an offered passage, never generated by the model.
    evidence_start: int | None = Field(default=None, ge=0)


class Name(Supported):
    """One inventoried name, cited to a passage rather than to an occurrence.

    `quote` is the whole cited passage (B.1: extract's names[] items cite only a
    passage, never an occurrence anchor), so it is intentionally unbounded here --
    the 400-char cap belonged to the old 400-char-passage 'names'/'name_slots'
    stages, both dropped by B.6. ``source_mentions`` still does the real per-
    occurrence regex scan of the whole chapter to build durable mention anchors.
    """
    surface: str = Field(max_length=80)
    kind: str
    named: bool


class Names(Strict):
    names: list[Name]
    reviewed_kinds: list[str] = Field(default_factory=list)
    rejected: list[dict] = Field(default_factory=list)


class Decision(Supported):
    mention_id: str
    outcome: Literal['existing', 'new', 'unresolved']
    # Existing: offered entity ID. New: offered representative mention ID.
    target_id: str | None
    quote: str
    reason: str = Field(max_length=MAX_EXPLANATION_CHARS)


class Claim(Supported):
    """Application-materialized proposal, ready for validate_proposals/publish.

    `type` is set structurally by the caller from which of B.1's three routing lists
    (attributes/relations/occurrences) produced this item -- never a model-chosen
    field. Keeping this shape (rather than reintroducing a wire-level enum) is a
    deliberate B.1 decision: see ExtractAttribute/ExtractRelation/ExtractOccurrence
    below for the model-facing contract that actually produces these.
    """
    type: Literal['fact', 'relationship', 'event']
    # Facts/relationships require exact-count subjects (1/2), enforced structurally
    # in validate_proposals rather than here; an occurrence may legitimately name no
    # participant at all ("it began to rain"), so this stays unconstrained.
    mention_ids: list[str] = Field(default_factory=list)
    attribute: str
    value: str = Field(max_length=MAX_FACT_VALUE_CHARS)
    # Display only. `value` stays source-language; an absent or wrong gloss never
    # blocks publication. Now populated directly from the extract schema (B.6) --
    # there is no separate render/render_verify pass to fall back on.
    value_en: str = Field(default='', max_length=MAX_FACT_GLOSS_CHARS)
    quote: str
    sentiment: int | None = Field(default=None, ge=-1, le=1)


class OccurrenceRef(Strict):
    """Response-local occurrence anchor; never a durable identity binding."""
    name_index: int = Field(ge=0)
    passage_id: str
    occurrence_index: int = Field(ge=0)


class ExtractName(Strict):
    surface: str = Field(min_length=1, max_length=80)
    kind: str
    passage_id: str


class ExtractAttribute(Strict):
    subject_ref: OccurrenceRef
    attribute: str = Field(pattern=r'^[a-z][a-z0-9_]{1,39}$')
    value: str = Field(max_length=400)
    value_en: str = Field(default='', max_length=200)
    passage_ids: list[str] = Field(min_length=1, max_length=2)


class ExtractRelation(Strict):
    src_ref: OccurrenceRef
    dst_ref: OccurrenceRef
    relation: str = Field(pattern=r'^[a-z][a-z0-9_]{1,39}$')
    sentiment: int | None = Field(default=None, ge=-1, le=1)
    passage_ids: list[str] = Field(min_length=1, max_length=2)


class ExtractOccurrence(Strict):
    summary: str = Field(max_length=400)
    summary_en: str = Field(default='', max_length=200)
    participant_refs: list[OccurrenceRef] = Field(default_factory=list, max_length=8)
    passage_ids: list[str] = Field(min_length=1, max_length=2)


class ExtractProposals(Strict):
    """Merged proposal response; refs are normalized by the application.

    Field ceilings are the hosted upper bound (B.4's provisional experimental caps).
    The wire schema actually offered to the model tightens `maxItems` per request
    (local vs hosted) via PassageContract.schema's `limits` argument; these Field
    bounds only need to admit whichever ceiling was actually offered.
    """
    names: list[ExtractName] = Field(default_factory=list, max_length=64)
    attributes: list[ExtractAttribute] = Field(default_factory=list, max_length=48)
    relations: list[ExtractRelation] = Field(default_factory=list, max_length=24)
    occurrences: list[ExtractOccurrence] = Field(default_factory=list, max_length=32)


class Proposals(Strict):
    decisions: list[Decision]
    claims: list[Claim]


class IdentityDecision(Strict):
    """Bounded model wire decision; refs exist only for one request."""

    occurrence_ref: str
    outcome: Literal['existing', 'new', 'unresolved']
    target_ref: str | None
    reason_code: Literal[
        'existing_evidence', 'new_first_appearance', 'new_coreference',
        'ambiguous', 'insufficient_evidence',
    ]
    explanation: str = Field(max_length=MAX_EXPLANATION_CHARS)
    # Materialized from an application-offered passage reference.
    quote: str
    evidence_start: int | None = Field(default=None, ge=0)


class IdentityDecisions(Strict):
    decisions: list[IdentityDecision]


class Alignment(Supported):
    phrase: str
    occurrence: int = Field(ge=0)
    mention_id: str | None
    quote: str


class Alignments(Strict):
    # An unbounded list let a name that recurs often in one translated window (a
    # recurring protagonist, say) force the model to emit one object per occurrence
    # with no ceiling, which reliably exhausted num_predict and truncated the whole
    # response into unparseable partial JSON. The caller (_align_window) detects
    # saturation the same way extraction does and re-queries a smaller window for the
    # remainder. This Field ceiling is the hosted upper bound (B.4); the actual wire
    # schema sent to the model tightens `maxItems` per request via
    # PassageContract.schema's `limits` argument, local vs hosted.
    alignments: list[Alignment] = Field(max_length=96)


class Verdict(Strict):
    id: str
    supported: bool
    reason: str = Field(max_length=MAX_EXPLANATION_CHARS)


class Verification(Strict):
    verdicts: list[Verdict]


def passage(text: str, quote: str, *, anchor: int | None = None, start: int | None = None) -> dict | None:
    """Return only exact evidence; ambiguous repeated quotations need an anchor."""
    if not quote or not quote.strip():
        return None
    if start is not None:
        # Exact offsets resolve repeated passages without fuzzy matching or quote repair.
        starts = [start] if 0 <= start and text[start:start+len(quote)] == quote else []
    else:
        starts = [m.start() for m in re.finditer(re.escape(quote), text)]
    if anchor is not None:
        starts = [start for start in starts if start <= anchor < start + len(quote)]
    if len(starts) != 1:
        return None
    return dict(char_start=starts[0], char_end=starts[0]+len(quote), quote=quote)


def source_mentions(novel: str, chapter: int, source: str, names: Names, ontology: dict) -> list[dict]:
    found = {}
    conflicting = set()
    for name in names.names:
        if not name.named or name.kind not in ontology['kinds'] or not name.surface.strip():
            continue
        # Generic titles/pronouns can be contextual mentions, never reusable identities.
        if name.surface.casefold() in {'he','she','they','master','elder','father','mother','他','她','长老','师父','父亲','母亲'}:
            continue
        if name.surface not in name.quote or not passage(source, name.quote, start=name.evidence_start):
            continue
        for match in re.finditer(re.escape(name.surface), source):
            start, end = match.span()
            if not CJK_RE.search(name.surface):
                word=lambda ch: ch.isalnum() or ch=='_'
                if ((word(name.surface[0]) and start>0 and word(source[start-1]))
                    or (word(name.surface[-1]) and end<len(source) and word(source[end]))):
                    continue
            # Supply local context for EACH occurrence; don't bind all homonyms together.
            left = max(source.rfind('。', 0, start), source.rfind('\n', 0, start)) + 1
            right = source.find('。', end)
            right = min(len(source), right+1 if right >= 0 else end+180)
            quote = source[left:right]
            mid = stable_id(novel, chapter, digest(source), start, end)
            if mid in conflicting:
                continue
            if mid in found and found[mid]['kind']!=name.kind:
                # Conflicting proposed kinds cannot be resolved by list order.
                del found[mid]
                conflicting.add(mid)
                continue
            found[mid] = dict(id=mid, surface=name.surface, kind=name.kind,
                              char_start=start, char_end=end, quote=quote,
                              context_start=left, context_end=right)
    return sorted(found.values(), key=lambda m: m['char_start'])


# B.2.2 -- indefinite/quantified-subject reject. A language heuristic, not a proof:
# preserve numeral-bearing proper names (techniques, organizations) by anchoring on
# a LEADING numeral/classifier only, never a bare substring match anywhere in the
# surface. Uncertain cases are not covered here and stay held for human review, same
# as everything else -- this only catches the clear cases the plan names.
_QUANTITY_EN = re.compile(
    r'^(?:\d+|dozens?|hundreds?|thousands?|several|many|numerous|a\s+(?:group|handful|few|couple)\s+of)\b',
    re.IGNORECASE)
_QUANTITY_ZH = re.compile(r'^(?:[〇零一二两三四五六七八九十百千万亿0-9]+[个只名位群批批伙帮]|数十|数百|数千|几|许多|一群|一片|一伙|一帮)')


def quantified_subject(surface: str) -> bool:
    surface = (surface or '').strip()
    return bool(surface and (_QUANTITY_EN.match(surface) or _QUANTITY_ZH.match(surface)))


# B.2.3 -- transient-predicate demotion. Not a reject: callers convert a matching
# fact deterministically into an event (preserving value/value_en, subject and
# evidence) rather than dropping it. Ambiguous cases stay held, same discipline.
_TRANSIENT_EN = re.compile(
    r'\b(?:patrolling|circling|hovering|currently|right now|at (?:this|that) moment)\b',
    re.IGNORECASE)
_TRANSIENT_ZH = re.compile(r'(正在|围绕着|巡逻|盘旋)')


def transient_predicate(value: str) -> bool:
    value = value or ''
    return bool(_TRANSIENT_EN.search(value) or _TRANSIENT_ZH.search(value))


# B.2.4 -- copied-sentence review flag. Length alone must not reject; this only
# marks an item for human attention, same accepted item either way.
COPIED_SENTENCE_CHARS = 200


def validate_proposals(source: str, mentions: list[dict], candidates: list[dict] | dict[str, list[dict]],
                       proposals: Proposals, ontology: dict, vocabulary: dict | None = None) -> tuple[list[dict], list[dict]]:
    """Structural checks and review-flag heuristics (B.2). Never durability/support proof.

    `mentions` must already be restricted to independently *verified* occurrences
    (B.1's anchored-subject rule): an unresolved or rejected mention is simply not
    `offered`, so any claim citing it is rejected below as an unoffered reference.
    """
    offered = {m['id']: m for m in mentions}
    if isinstance(candidates, dict):
        per_mention = {
            mention_id: {candidate['id']: candidate for candidate in rows}
            for mention_id, rows in candidates.items()
        }
        entities = {candidate_id: candidate for rows in per_mention.values()
                    for candidate_id, candidate in rows.items()}
    else:
        entities = {c['id']: c for c in candidates}
        per_mention = {mention_id: entities for mention_id in offered}
    accepted, rejected = [], []
    seen = set()
    for i, d in enumerate(proposals.decisions):
        m = offered.get(d.mention_id)
        why = None
        if not m or d.mention_id in seen:
            why = 'unknown or duplicate mention ID'
        elif d.outcome == 'unresolved':
            seen.add(d.mention_id)
            continue
        elif not passage(source, d.quote, anchor=m['char_start'], start=d.evidence_start):
            why = 'identity evidence does not include this occurrence'
        elif d.outcome == 'existing':
            c = per_mention.get(d.mention_id, {}).get(d.target_id)
            if not c or c['kind'] != m['kind']:
                why = 'invented candidate ID or incompatible kind'
        elif d.outcome == 'new':
            root = offered.get(d.target_id)
            if not root or root['kind'] != m['kind']:
                why = 'new identity must reference an offered mention of the same kind'
        seen.add(d.mention_id)
        item = dict(id=f'identity:{i}', **d.model_dump())
        (rejected if why else accepted).append(dict(item, rejection=why) if why else item)
    for i, c in enumerate(proposals.claims):
        why = None
        flags = []
        demote = False
        if any(mid not in offered for mid in c.mention_ids):
            why = 'claim references an unoffered mention ID'
        elif not passage(source, c.quote, start=c.evidence_start):
            why = 'claim evidence is absent or ambiguous'
        elif c.mention_ids and quantified_subject(offered[c.mention_ids[0]].get('surface','')):
            # B.2.2: reject clear quantity/classifier subjects. The information is not
            # lost -- it may still surface as an occurrence's free-text summary.
            why = 'quantified or indefinite subject cannot anchor a durable assertion'
        elif c.type == 'fact':
            row = (vocabulary or {}).get(('attribute', c.attribute)) if vocabulary else None
            syntactic = bool(re.fullmatch(r'^[a-z][a-z0-9_]{1,39}$', c.attribute))
            compatible = (len(c.mention_ids) == 1 and c.mention_ids[0] in offered and
                          (row is None or offered[c.mention_ids[0]]['kind'] in (row.get('kinds') or [])))
            if row and row.get('status') in {'banned','retired'}:
                why = 'vocabulary term is banned or retired'
            elif len(c.mention_ids) != 1 or not syntactic or not compatible:
                why = 'invalid attribute or entity kind'
            elif transient_predicate(c.value):
                # B.2.3: demote deterministically rather than reject. Same subject,
                # evidence and qualifiers; value/value_en become the event summary.
                demote = True
                flags.append('transient_predicate_demoted_to_event')
            elif len(c.value) >= COPIED_SENTENCE_CHARS:
                # B.2.4: flag only. A long verbatim value may still be a valid durable
                # statement; a human, not sentence length, decides.
                flags.append('long_verbatim_value')
        elif c.type == 'relationship':
            row = (vocabulary or {}).get(('relation', c.attribute)) if vocabulary else None
            syntactic = bool(re.fullmatch(r'^[a-z][a-z0-9_]{1,39}$', c.attribute))
            compatible = (len(c.mention_ids) == 2 and all(mid in offered for mid in c.mention_ids) and
                          (row is None or
                           (offered[c.mention_ids[0]]['kind'] in (row.get('kinds') or []) and
                            offered[c.mention_ids[1]]['kind'] in (row.get('dst_kinds') or []))))
            if row and row.get('status') in {'banned','retired'}:
                why = 'vocabulary term is banned or retired'
            elif len(c.mention_ids) != 2 or not syntactic or not compatible:
                why = 'invalid relationship'
        elif c.type == 'event':
            if len(c.mention_ids) > 8:
                why = 'occurrence cites more participants than offered'
        item = dict(id=f'claim:{i}', **c.model_dump())
        if why:
            rejected.append(dict(item, rejection=why))
            continue
        if demote:
            item = dict(item, type='event', attribute='', mention_ids=item['mention_ids'][:1],
                        review_flags=flags)
        elif flags:
            item = dict(item, review_flags=flags)
        accepted.append(item)
    return accepted, rejected


def approved(items: list[dict], verification: Verification) -> tuple[list[dict], list[dict]]:
    """Missing, repeated, or negative verdicts fail closed."""
    verdicts: dict[str, list[Verdict]] = {}
    for v in verification.verdicts:
        verdicts.setdefault(v.id, []).append(v)
    yes, no = [], []
    for item in items:
        vs = verdicts.get(item['id'], [])
        if len(vs) == 1 and vs[0].supported:
            yes.append(item)
        else:
            no.append(dict(item, rejection=vs[0].reason if len(vs)==1 else 'missing or duplicate verification'))
    return yes, no


def aligned_mentions(novel: str, chapter: int, source: str, display: str,
                     mentions: list[dict], alignment: Alignments, *,
                     display_offset: int = 0, display_identity: str | None = None) -> list[dict]:
    offered = {m['id']: m for m in mentions}
    spans = {}
    for a in alignment.alignments:
        if not a.phrase.strip():
            continue
        matches = list(re.finditer(re.escape(a.phrase), display))
        if a.occurrence >= len(matches):
            continue
        start, end = matches[a.occurrence].span()
        start, end = start+display_offset, end+display_offset
        mid = a.mention_id
        m = offered.get(mid)
        ev = passage(source, a.quote, anchor=m['char_start'], start=a.evidence_start) if m else None
        # Invalid alignment still yields an empty clickable card, never a guessed link.
        item = dict(id=stable_id(novel,chapter,display_identity or digest(display),start,end),
                    char_start=start,char_end=end,phrase=a.phrase,
                    mention_id=mid if ev else None,quote=a.quote if ev else None,
                    evidence_start=a.evidence_start if ev else None)
        key = (start,end)
        if key in spans and spans[key]['mention_id'] != item['mention_id']:
            item['mention_id'] = item['quote'] = None
        spans[key] = item
    result = []
    for item in sorted(spans.values(), key=lambda s: (s['char_start'], -s['char_end'])):
        if result and item['char_start'] < result[-1]['char_end']:
            continue
        result.append(item)
    return result
