# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: textproc.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'textproc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etextproc.proto\x12\x08textproc\"*\n\x05\x41lias\x12\x10\n\x08\x61lias_id\x18\x01 \x01(\t\x12\x0f\n\x07surface\x18\x02 \x01(\t\"R\n\x12MentionScanRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12 \n\x07\x61liases\x18\x02 \x03(\x0b\x32\x0f.textproc.Alias\x12\x0c\n\x04lang\x18\x03 \x01(\t\"d\n\x04Span\x12\x10\n\x08\x61lias_id\x18\x01 \x01(\t\x12\x12\n\nbyte_start\x18\x02 \x01(\r\x12\x10\n\x08\x62yte_end\x18\x03 \x01(\r\x12\x12\n\nchar_start\x18\x04 \x01(\r\x12\x10\n\x08\x63har_end\x18\x05 \x01(\r\"4\n\x13MentionScanResponse\x12\x1d\n\x05spans\x18\x01 \x03(\x0b\x32\x0e.textproc.Span\"\x1b\n\x0bHashRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"4\n\x0cHashResponse\x12\x0e\n\x06sha256\x18\x01 \x01(\t\x12\x14\n\x0cnear_dup_sig\x18\x02 \x01(\t\"I\n\x0cRetroRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12+\n\x0creplacements\x18\x02 \x03(\x0b\x32\x15.textproc.Replacement\"\'\n\x0bReplacement\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\"\x1d\n\rRetroResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2\xda\x01\n\x08TextProc\x12K\n\x0cScanMentions\x12\x1c.textproc.MentionScanRequest\x1a\x1d.textproc.MentionScanResponse\x12\x43\n\x10\x41pplyRetroUpdate\x12\x16.textproc.RetroRequest\x1a\x17.textproc.RetroResponse\x12<\n\x0bHashContent\x12\x15.textproc.HashRequest\x1a\x16.textproc.HashResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'textproc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALIAS']._serialized_start=28
  _globals['_ALIAS']._serialized_end=70
  _globals['_MENTIONSCANREQUEST']._serialized_start=72
  _globals['_MENTIONSCANREQUEST']._serialized_end=154
  _globals['_SPAN']._serialized_start=156
  _globals['_SPAN']._serialized_end=256
  _globals['_MENTIONSCANRESPONSE']._serialized_start=258
  _globals['_MENTIONSCANRESPONSE']._serialized_end=310
  _globals['_HASHREQUEST']._serialized_start=312
  _globals['_HASHREQUEST']._serialized_end=339
  _globals['_HASHRESPONSE']._serialized_start=341
  _globals['_HASHRESPONSE']._serialized_end=393
  _globals['_RETROREQUEST']._serialized_start=395
  _globals['_RETROREQUEST']._serialized_end=468
  _globals['_REPLACEMENT']._serialized_start=470
  _globals['_REPLACEMENT']._serialized_end=509
  _globals['_RETRORESPONSE']._serialized_start=511
  _globals['_RETRORESPONSE']._serialized_end=540
  _globals['_TEXTPROC']._serialized_start=543
  _globals['_TEXTPROC']._serialized_end=761
# @@protoc_insertion_point(module_scope)
