# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pipeline import textproc_pb2 as textproc__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in textproc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TextProcStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScanMentions = channel.unary_unary(
                '/textproc.TextProc/ScanMentions',
                request_serializer=textproc__pb2.MentionScanRequest.SerializeToString,
                response_deserializer=textproc__pb2.MentionScanResponse.FromString,
                _registered_method=True)
        self.ApplyRetroUpdate = channel.unary_unary(
                '/textproc.TextProc/ApplyRetroUpdate',
                request_serializer=textproc__pb2.RetroRequest.SerializeToString,
                response_deserializer=textproc__pb2.RetroResponse.FromString,
                _registered_method=True)
        self.HashContent = channel.unary_unary(
                '/textproc.TextProc/HashContent',
                request_serializer=textproc__pb2.HashRequest.SerializeToString,
                response_deserializer=textproc__pb2.HashResponse.FromString,
                _registered_method=True)


class TextProcServicer:
    """Missing associated documentation comment in .proto file."""

    def ScanMentions(self, request, context):
        """Aho-Corasick over an alias set → mention spans, for retrieve-then-resolve.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyRetroUpdate(self, request, context):
        """Deterministic canonical-term replacement across cached translations (retro-update).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HashContent(self, request, context):
        """Content hashing / near-dup detection for cache keys + scrape stop-conditions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextProcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScanMentions': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanMentions,
                    request_deserializer=textproc__pb2.MentionScanRequest.FromString,
                    response_serializer=textproc__pb2.MentionScanResponse.SerializeToString,
            ),
            'ApplyRetroUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyRetroUpdate,
                    request_deserializer=textproc__pb2.RetroRequest.FromString,
                    response_serializer=textproc__pb2.RetroResponse.SerializeToString,
            ),
            'HashContent': grpc.unary_unary_rpc_method_handler(
                    servicer.HashContent,
                    request_deserializer=textproc__pb2.HashRequest.FromString,
                    response_serializer=textproc__pb2.HashResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'textproc.TextProc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('textproc.TextProc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TextProc:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScanMentions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/textproc.TextProc/ScanMentions',
            textproc__pb2.MentionScanRequest.SerializeToString,
            textproc__pb2.MentionScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyRetroUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/textproc.TextProc/ApplyRetroUpdate',
            textproc__pb2.RetroRequest.SerializeToString,
            textproc__pb2.RetroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HashContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/textproc.TextProc/HashContent',
            textproc__pb2.HashRequest.SerializeToString,
            textproc__pb2.HashResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
