-- Permissions for restoring a snapshot from this release with --no-acl.
GRANT USAGE ON SCHEMA public TO rls_reader;
GRANT USAGE ON SCHEMA public TO reader_progress_writer;
GRANT USAGE ON SCHEMA public TO book_auth;
GRANT USAGE ON SCHEMA public TO book_dispatcher;
GRANT USAGE ON SCHEMA public TO book_cleanup;
REVOKE ALL ON FUNCTION public.account_active() FROM PUBLIC;
GRANT ALL ON FUNCTION public.account_active() TO ingest_writer;
GRANT ALL ON FUNCTION public.account_active() TO rls_reader;
GRANT ALL ON FUNCTION public.account_active() TO reader_progress_writer;
GRANT ALL ON FUNCTION public.account_active() TO book_dispatcher;
REVOKE ALL ON FUNCTION public.guard_edge_supersession() FROM PUBLIC;
GRANT ALL ON FUNCTION public.reader_chapter() TO rls_reader;
GRANT ALL ON FUNCTION public.reader_novel() TO rls_reader;
REVOKE ALL ON FUNCTION public.request_account_deletion(actor uuid) FROM PUBLIC;
GRANT ALL ON FUNCTION public.request_account_deletion(actor uuid) TO book_auth;
REVOKE ALL ON FUNCTION public.worker_catalog() FROM PUBLIC;
GRANT ALL ON FUNCTION public.worker_catalog() TO book_worker;
REVOKE ALL ON FUNCTION public.worker_due_retries(generic_limit integer, provider_limit integer) FROM PUBLIC;
GRANT ALL ON FUNCTION public.worker_due_retries(generic_limit integer, provider_limit integer) TO book_worker;
REVOKE ALL ON FUNCTION public.worker_novel_owner(requested uuid) FROM PUBLIC;
GRANT ALL ON FUNCTION public.worker_novel_owner(requested uuid) TO book_worker;
REVOKE ALL ON FUNCTION public.worker_scrape_catalog() FROM PUBLIC;
GRANT ALL ON FUNCTION public.worker_scrape_catalog() TO book_worker;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.account TO book_auth;
GRANT SELECT ON TABLE public.account TO book_dispatcher;
GRANT SELECT ON TABLE public.account TO ingest_writer;
GRANT SELECT ON TABLE public.account TO rls_reader;
GRANT SELECT ON TABLE public.account TO reader_progress_writer;
GRANT SELECT,DELETE,UPDATE ON TABLE public.account TO book_cleanup;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.account_cleanup TO ingest_writer;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.account_cleanup TO book_cleanup;
GRANT SELECT,USAGE ON SEQUENCE public.account_cleanup_id_seq TO ingest_writer;
GRANT SELECT,USAGE ON SEQUENCE public.account_cleanup_id_seq TO book_cleanup;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.account_invitation TO book_auth;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.account_oauth_state TO book_auth;
GRANT SELECT ON TABLE public.account_queue_control TO book_dispatcher;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.account_queue_control TO ingest_writer;
GRANT SELECT ON TABLE public.account_queue_control TO rls_reader;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.account_session TO book_auth;
GRANT SELECT,INSERT ON TABLE public.account_usage TO ingest_writer;
GRANT SELECT,INSERT ON TABLE public.account_usage TO rls_reader;
GRANT SELECT,USAGE ON SEQUENCE public.account_usage_id_seq TO ingest_writer;
GRANT USAGE ON SEQUENCE public.account_usage_id_seq TO rls_reader;
GRANT SELECT ON TABLE public.chapter TO reader_progress_writer;
GRANT SELECT ON TABLE public.chapter TO book_dispatcher;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.chapter TO ingest_writer;
GRANT SELECT(novel_id) ON TABLE public.chapter TO rls_reader;
GRANT SELECT(chapter_index) ON TABLE public.chapter TO rls_reader;
GRANT SELECT(translation_ready) ON TABLE public.chapter TO rls_reader;
GRANT SELECT(enrichment_attempts) ON TABLE public.chapter TO rls_reader;
GRANT SELECT(enrichment_retry_at) ON TABLE public.chapter TO rls_reader;
GRANT SELECT(provider_retry_attempts) ON TABLE public.chapter TO rls_reader;
GRANT SELECT(provider_retry_at) ON TABLE public.chapter TO rls_reader;
GRANT SELECT(provider_retry_category) ON TABLE public.chapter TO rls_reader;
GRANT SELECT(enrichment_discarded) ON TABLE public.chapter TO rls_reader;
GRANT SELECT(facts_count) ON TABLE public.chapter TO rls_reader;
GRANT SELECT,INSERT,DELETE ON TABLE public.chapter_fact TO ingest_writer;
GRANT SELECT ON TABLE public.chapter_fact TO rls_reader;
GRANT SELECT,INSERT,DELETE ON TABLE public.chapter_failure TO ingest_writer;
GRANT SELECT(id) ON TABLE public.chapter_failure TO reader_progress_writer;
GRANT SELECT(id) ON TABLE public.chapter_failure TO rls_reader;
GRANT SELECT(novel_id) ON TABLE public.chapter_failure TO reader_progress_writer;
GRANT SELECT(novel_id) ON TABLE public.chapter_failure TO rls_reader;
GRANT SELECT(chapter_index) ON TABLE public.chapter_failure TO reader_progress_writer;
GRANT SELECT(chapter_index) ON TABLE public.chapter_failure TO rls_reader;
GRANT SELECT(error_code) ON TABLE public.chapter_failure TO reader_progress_writer;
GRANT SELECT(error_code) ON TABLE public.chapter_failure TO rls_reader;
GRANT SELECT(occurred_at) ON TABLE public.chapter_failure TO reader_progress_writer;
GRANT SELECT(occurred_at) ON TABLE public.chapter_failure TO rls_reader;
GRANT SELECT,USAGE ON SEQUENCE public.chapter_failure_id_seq TO ingest_writer;
GRANT SELECT ON TABLE public.chapter_translation_version TO rls_reader;
GRANT SELECT,INSERT,DELETE ON TABLE public.chapter_translation_version TO ingest_writer;
GRANT SELECT,INSERT ON TABLE public.character_name_checkpoint TO ingest_writer;
GRANT SELECT ON TABLE public.character_name_occurrence TO rls_reader;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.character_name_occurrence TO ingest_writer;
GRANT SELECT ON TABLE public.character_name_review TO rls_reader;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.character_name_review TO ingest_writer;
GRANT SELECT ON TABLE public.chunk TO rls_reader;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.chunk TO ingest_writer;
GRANT SELECT(embedding_space) ON TABLE public.chunk TO rls_reader;
GRANT SELECT,USAGE ON SEQUENCE public.chunk_id_seq TO ingest_writer;
GRANT SELECT ON TABLE public.embedding_config TO rls_reader;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.embedding_config TO ingest_writer;
GRANT SELECT,INSERT,DELETE ON TABLE public.fact_retraction TO ingest_writer;
GRANT SELECT ON TABLE public.fact_retraction TO rls_reader;
GRANT SELECT ON TABLE public.glossary TO rls_reader;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.glossary TO ingest_writer;
GRANT SELECT ON TABLE public.glossary_candidate TO rls_reader;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.glossary_candidate TO ingest_writer;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.glossary_candidate_chapter TO ingest_writer;
GRANT SELECT,INSERT,DELETE ON TABLE public.glossary_changelog TO ingest_writer;
GRANT SELECT,USAGE ON SEQUENCE public.glossary_changelog_id_seq TO ingest_writer;
GRANT SELECT ON TABLE public.job TO book_dispatcher;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.job TO ingest_writer;
GRANT SELECT ON TABLE public.mention_span TO rls_reader;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.mention_span TO ingest_writer;
GRANT SELECT,USAGE ON SEQUENCE public.mention_span_id_seq TO ingest_writer;
GRANT SELECT ON TABLE public.novel TO rls_reader;
GRANT SELECT ON TABLE public.novel TO reader_progress_writer;
GRANT SELECT ON TABLE public.novel TO book_dispatcher;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.novel TO ingest_writer;
GRANT SELECT,DELETE ON TABLE public.novel TO book_cleanup;
GRANT SELECT(owner_id) ON TABLE public.novel TO rls_reader;
GRANT SELECT(owner_id) ON TABLE public.novel TO reader_progress_writer;
GRANT SELECT ON TABLE public.novel_provider_config TO rls_reader;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.novel_provider_config TO ingest_writer;
GRANT SELECT ON TABLE public.provider_credential TO rls_reader;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.provider_credential TO ingest_writer;
GRANT SELECT,INSERT,UPDATE ON TABLE public.reader_progress TO reader_progress_writer;
GRANT SELECT ON TABLE public.reader_progress TO ingest_writer;
GRANT SELECT ON TABLE public.scrape_job TO rls_reader;
GRANT SELECT,INSERT ON TABLE public.scrape_job TO reader_progress_writer;
GRANT SELECT ON TABLE public.scrape_job TO book_dispatcher;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.scrape_job TO ingest_writer;
GRANT UPDATE(cancel_requested) ON TABLE public.scrape_job TO reader_progress_writer;
GRANT SELECT,USAGE ON SEQUENCE public.scrape_job_id_seq TO reader_progress_writer;
GRANT SELECT,USAGE ON SEQUENCE public.scrape_job_id_seq TO ingest_writer;
GRANT SELECT,INSERT,DELETE ON TABLE public.subject TO ingest_writer;
GRANT SELECT ON TABLE public.subject TO rls_reader;
GRANT SELECT ON TABLE public.term_rendering_occurrence TO rls_reader;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.term_rendering_occurrence TO ingest_writer;
GRANT SELECT,INSERT,DELETE ON TABLE public.wiki_page TO ingest_writer;
GRANT SELECT ON TABLE public.wiki_page TO rls_reader;
GRANT CREATE ON SCHEMA public TO book_dispatcher,book_cleanup;
ALTER FUNCTION public.worker_novel_owner(uuid) OWNER TO book_dispatcher;
ALTER FUNCTION public.worker_catalog() OWNER TO book_dispatcher;
ALTER FUNCTION public.worker_due_retries(integer,integer) OWNER TO book_dispatcher;
ALTER FUNCTION public.worker_scrape_catalog() OWNER TO book_dispatcher;
ALTER FUNCTION public.request_account_deletion(uuid) OWNER TO book_cleanup;
REVOKE CREATE ON SCHEMA public FROM book_dispatcher,book_cleanup;
GRANT SELECT,INSERT ON account_deletion_tombstone TO book_cleanup;
GRANT USAGE ON SCHEMA public TO book_backup;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO book_backup;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO book_backup;
GRANT USAGE ON SCHEMA public TO book_maintenance;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO book_maintenance;
GRANT USAGE,SELECT,UPDATE ON ALL SEQUENCES IN SCHEMA public TO book_maintenance;
GRANT EXECUTE ON FUNCTION request_account_deletion(uuid) TO book_maintenance;
